# -*- coding: utf-8 -*-
"""Led_blink.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1byehTAjHW0PREWw-HPxYWItK-5L1h24r
"""

# Importar librerías
import RPi.GPIO as GPIO
import time

# Configuración de numeración BCM
GPIO.setmode(GPIO.BCM)

# Definir pines
LED = 17       # LED en pin GPIO17
BOTON = 18     # Botón en pin GPIO18

# Configurar el LED como salida
GPIO.setup(LED, GPIO.OUT)

# Configurar el botón como entrada con resistencia pull-down
GPIO.setup(BOTON, GPIO.IN, pull_up_down=GPIO.PUD_DOWN)

print("Presiona el botón para encender el LED en modo parpadeo...")

try:
    while True:
        if GPIO.input(BOTON) == GPIO.HIGH:  # Si el botón está presionado
            print("Botón presionado: LED parpadeando")
            # Mientras el botón esté presionado, el LED parpadea
            while GPIO.input(BOTON) == GPIO.HIGH:
                GPIO.output(LED, GPIO.HIGH)
                time.sleep(0.3)
                GPIO.output(LED, GPIO.LOW)
                time.sleep(0.3)
        else:
            # Si no se presiona, el LED permanece apagado
            GPIO.output(LED, GPIO.LOW)
except KeyboardInterrupt:
    print("\nPrograma interrumpido")

finally:
    # Liberar los pines al salir
    GPIO.cleanup()